name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Need qmake and QT
        run: | 
            sudo apt install -y qt5-qmake qtbase5-dev qtbase5-dev-tools
            export PREFIX = /usr/share

      - name: qmake
        run: qmake

      - name: make
        run: make

      - name: make check
        run: make check

      - name: make install
        run: sudo make install
      
      - name: Version
        run: echo "::set-output name=version::$(head -n 1 ./HNEWizard.pro| cut -d ' ' -f 3)"
        id: version

      - name: Archive of bin's
        run: | 
            tar -czvf HNEWizard-bin-${{ steps.version.outputs.version }}.tar.gz /usr/bin/HNEWizard
            ls -lah

      - name: Create Github Release
        uses: ncipollo/release-action@v1.11.1
        id: create_release
        with:
          artifacts: "HNEWizard-bin-${{ steps.version.outputs.version }}*"
          replacesArtifacts: true
          token: ${{ github.TOKEN }}
          allowUpdates: true
          name: ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          body: "Automatic build from GitHub action"
